/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SellRouteImport } from './routes/sell'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountEnquiriesRouteImport } from './routes/account.enquiries'
import { Route as AccountFavouritesRouteImport } from './routes/account.favourites'
import { Route as AccountTestDrivesRouteImport } from './routes/account.test-drives'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCarsRouteImport } from './routes/admin.cars'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminTestDrivesRouteImport } from './routes/admin.test-drives'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CarsIndexRouteImport } from './routes/cars.index'
import { Route as CarsCarIdRouteImport } from './routes/cars.$carId'
import { Route as SellIndexRouteImport } from './routes/sell.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as SellCarsIndexRouteImport } from './routes/sell.cars.index'
import { Route as SellCarsNewRouteImport } from './routes/sell.cars.new'
import { Route as SellCarsCarIdEditRouteImport } from './routes/sell.cars.$carId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountEnquiriesRoute = AccountEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AccountRoute,
} as any)
const AccountFavouritesRoute = AccountFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => AccountRoute,
} as any)
const AccountTestDrivesRoute = AccountTestDrivesRouteImport.update({
  id: '/test-drives',
  path: '/test-drives',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarsRoute = AdminCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestDrivesRoute = AdminTestDrivesRouteImport.update({
  id: '/test-drives',
  path: '/test-drives',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsCarIdRoute = CarsCarIdRouteImport.update({
  id: '/cars/$carId',
  path: '/cars/$carId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIndexRoute = SellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const SellCarsIndexRoute = SellCarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => SellRoute,
} as any)
const SellCarsNewRoute = SellCarsNewRouteImport.update({
  id: '/cars/new',
  path: '/cars/new',
  getParentRoute: () => SellRoute,
} as any)
const SellCarsCarIdEditRoute = SellCarsCarIdEditRouteImport.update({
  id: '/cars/$carId/edit',
  path: '/cars/$carId/edit',
  getParentRoute: () => SellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sell': typeof SellRouteWithChildren
  '/account/enquiries': typeof AccountEnquiriesRoute
  '/account/favourites': typeof AccountFavouritesRoute
  '/account/test-drives': typeof AccountTestDrivesRoute
  '/admin/cars': typeof AdminCarsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/test-drives': typeof AdminTestDrivesRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/cars/$carId': typeof CarsCarIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/sell/': typeof SellIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/sell/cars/new': typeof SellCarsNewRoute
  '/sell/cars/': typeof SellCarsIndexRoute
  '/sell/cars/$carId/edit': typeof SellCarsCarIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/enquiries': typeof AccountEnquiriesRoute
  '/account/favourites': typeof AccountFavouritesRoute
  '/account/test-drives': typeof AccountTestDrivesRoute
  '/admin/cars': typeof AdminCarsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/test-drives': typeof AdminTestDrivesRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/cars/$carId': typeof CarsCarIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/cars': typeof CarsIndexRoute
  '/sell': typeof SellIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/sell/cars/new': typeof SellCarsNewRoute
  '/sell/cars': typeof SellCarsIndexRoute
  '/sell/cars/$carId/edit': typeof SellCarsCarIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sell': typeof SellRouteWithChildren
  '/account/enquiries': typeof AccountEnquiriesRoute
  '/account/favourites': typeof AccountFavouritesRoute
  '/account/test-drives': typeof AccountTestDrivesRoute
  '/admin/cars': typeof AdminCarsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/test-drives': typeof AdminTestDrivesRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/cars/$carId': typeof CarsCarIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/sell/': typeof SellIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/sell/cars/new': typeof SellCarsNewRoute
  '/sell/cars/': typeof SellCarsIndexRoute
  '/sell/cars/$carId/edit': typeof SellCarsCarIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/login'
    | '/register'
    | '/sell'
    | '/account/enquiries'
    | '/account/favourites'
    | '/account/test-drives'
    | '/admin/cars'
    | '/admin/enquiries'
    | '/admin/test-drives'
    | '/admin/users'
    | '/cars/$carId'
    | '/account/'
    | '/admin/'
    | '/cars/'
    | '/sell/'
    | '/admin/users/$userId'
    | '/sell/cars/new'
    | '/sell/cars/'
    | '/sell/cars/$carId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/account/enquiries'
    | '/account/favourites'
    | '/account/test-drives'
    | '/admin/cars'
    | '/admin/enquiries'
    | '/admin/test-drives'
    | '/admin/users'
    | '/cars/$carId'
    | '/account'
    | '/admin'
    | '/cars'
    | '/sell'
    | '/admin/users/$userId'
    | '/sell/cars/new'
    | '/sell/cars'
    | '/sell/cars/$carId/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/login'
    | '/register'
    | '/sell'
    | '/account/enquiries'
    | '/account/favourites'
    | '/account/test-drives'
    | '/admin/cars'
    | '/admin/enquiries'
    | '/admin/test-drives'
    | '/admin/users'
    | '/cars/$carId'
    | '/account/'
    | '/admin/'
    | '/cars/'
    | '/sell/'
    | '/admin/users/$userId'
    | '/sell/cars/new'
    | '/sell/cars/'
    | '/sell/cars/$carId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SellRoute: typeof SellRouteWithChildren
  CarsCarIdRoute: typeof CarsCarIdRoute
  CarsIndexRoute: typeof CarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/enquiries': {
      id: '/account/enquiries'
      path: '/enquiries'
      fullPath: '/account/enquiries'
      preLoaderRoute: typeof AccountEnquiriesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/favourites': {
      id: '/account/favourites'
      path: '/favourites'
      fullPath: '/account/favourites'
      preLoaderRoute: typeof AccountFavouritesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/test-drives': {
      id: '/account/test-drives'
      path: '/test-drives'
      fullPath: '/account/test-drives'
      preLoaderRoute: typeof AccountTestDrivesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cars': {
      id: '/admin/cars'
      path: '/cars'
      fullPath: '/admin/cars'
      preLoaderRoute: typeof AdminCarsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/test-drives': {
      id: '/admin/test-drives'
      path: '/test-drives'
      fullPath: '/admin/test-drives'
      preLoaderRoute: typeof AdminTestDrivesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$carId': {
      id: '/cars/$carId'
      path: '/cars/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof CarsCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/': {
      id: '/sell/'
      path: '/'
      fullPath: '/sell/'
      preLoaderRoute: typeof SellIndexRouteImport
      parentRoute: typeof SellRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/sell/cars/': {
      id: '/sell/cars/'
      path: '/cars'
      fullPath: '/sell/cars/'
      preLoaderRoute: typeof SellCarsIndexRouteImport
      parentRoute: typeof SellRoute
    }
    '/sell/cars/new': {
      id: '/sell/cars/new'
      path: '/cars/new'
      fullPath: '/sell/cars/new'
      preLoaderRoute: typeof SellCarsNewRouteImport
      parentRoute: typeof SellRoute
    }
    '/sell/cars/$carId/edit': {
      id: '/sell/cars/$carId/edit'
      path: '/cars/$carId/edit'
      fullPath: '/sell/cars/$carId/edit'
      preLoaderRoute: typeof SellCarsCarIdEditRouteImport
      parentRoute: typeof SellRoute
    }
  }
}

interface AccountRouteChildren {
  AccountEnquiriesRoute: typeof AccountEnquiriesRoute
  AccountFavouritesRoute: typeof AccountFavouritesRoute
  AccountTestDrivesRoute: typeof AccountTestDrivesRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountEnquiriesRoute: AccountEnquiriesRoute,
  AccountFavouritesRoute: AccountFavouritesRoute,
  AccountTestDrivesRoute: AccountTestDrivesRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminCarsRoute: typeof AdminCarsRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminTestDrivesRoute: typeof AdminTestDrivesRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCarsRoute: AdminCarsRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminTestDrivesRoute: AdminTestDrivesRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SellRouteChildren {
  SellIndexRoute: typeof SellIndexRoute
  SellCarsNewRoute: typeof SellCarsNewRoute
  SellCarsIndexRoute: typeof SellCarsIndexRoute
  SellCarsCarIdEditRoute: typeof SellCarsCarIdEditRoute
}

const SellRouteChildren: SellRouteChildren = {
  SellIndexRoute: SellIndexRoute,
  SellCarsNewRoute: SellCarsNewRoute,
  SellCarsIndexRoute: SellCarsIndexRoute,
  SellCarsCarIdEditRoute: SellCarsCarIdEditRoute,
}

const SellRouteWithChildren = SellRoute._addFileChildren(SellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SellRoute: SellRouteWithChildren,
  CarsCarIdRoute: CarsCarIdRoute,
  CarsIndexRoute: CarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
