"""initial

Revision ID: ec911d4bf3d0
Revises: 
Create Date: 2026-09-12 12:52:43.362103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec911d4bf3d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=30), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=False),
    sa.Column('transmission', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('is_negotiable', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('NOT (is_available = true AND is_sold = true)', name='ck_car_not_available_and_sold'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cars_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cars_is_available'), ['is_available'], unique=False)
        batch_op.create_index(batch_op.f('ix_cars_location'), ['location'], unique=False)
        batch_op.create_index('ix_cars_location_available', ['location', 'is_available'], unique=False)
        batch_op.create_index(batch_op.f('ix_cars_make'), ['make'], unique=False)
        batch_op.create_index('ix_cars_make_model_year', ['make', 'model', 'year'], unique=False)
        batch_op.create_index(batch_op.f('ix_cars_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_cars_price'), ['price'], unique=False)
        batch_op.create_index('ix_cars_price_available', ['price', 'is_available'], unique=False)
        batch_op.create_index(batch_op.f('ix_cars_year'), ['year'], unique=False)

    op.create_table('car_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('enquiry_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enquiries_car_id'), ['car_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiries_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_enquiries_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiries_user_id'), ['user_id'], unique=False)

    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'car_id', name='uq_favourite_user_car')
    )
    op.create_table('test_drives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=False),
    sa.Column('preferred_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_drives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_drives_car_id'), ['car_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_drives_preferred_date'), ['preferred_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_drives_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_drives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_drives_user_id'))
        batch_op.drop_index(batch_op.f('ix_test_drives_preferred_date'))
        batch_op.drop_index(batch_op.f('ix_test_drives_car_id'))

    op.drop_table('test_drives')
    op.drop_table('favourites')
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enquiries_user_id'))
        batch_op.drop_index('ix_enquiries_status_created')
        batch_op.drop_index(batch_op.f('ix_enquiries_created_at'))
        batch_op.drop_index(batch_op.f('ix_enquiries_car_id'))

    op.drop_table('enquiries')
    op.drop_table('car_images')
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cars_year'))
        batch_op.drop_index('ix_cars_price_available')
        batch_op.drop_index(batch_op.f('ix_cars_price'))
        batch_op.drop_index(batch_op.f('ix_cars_model'))
        batch_op.drop_index('ix_cars_make_model_year')
        batch_op.drop_index(batch_op.f('ix_cars_make'))
        batch_op.drop_index('ix_cars_location_available')
        batch_op.drop_index(batch_op.f('ix_cars_location'))
        batch_op.drop_index(batch_op.f('ix_cars_is_available'))
        batch_op.drop_index(batch_op.f('ix_cars_created_at'))

    op.drop_table('cars')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
